### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by jalalirs** [JasonObeid/Chart2Text#1]
I managed to run the entire preprocessing pipeline but when I train, I get the following error. Which pytorch version you use?

python model/train.py --model_path "experiments" --exp_name "chart2text" --exp_id "run1" --train_cs_table_path data/train/trainData.txt.pth --train_sm_table_path data/train/trainData.txt.pth --train_sm_summary_path data/train/trainSummary.txt.pth --valid_table_path data/valid/validData.txt.pth --valid_summary_path data/valid/validSummary.txt.pth --cs_step True --lambda_cs "1" --sm_step True --lambda_sm "1" --label_smoothing 0.05 --sm_step_with_cc_loss False --sm_step_with_cs_proba False --share_inout_emb True --share_srctgt_emb False --emb_dim 512 --enc_n_layers 1 --dec_n_layers 6 --dropout 0.1 --save_periodic 40 --batch_size 6 --beam_size 4 --epoch_size 1000 --max_epoch 81 --eval_bleu True --sinusoidal_embeddings True --encoder_positional_emb True --gelu_activation True --validation_metrics valid_mt_bleu

INFO - 02/11/21 07:40:26 - 0:00:00 - ============ Initialized logger ============

INFO - 02/11/21 07:40:26 - 0:00:00 - asm: False

                                     attention_dropout: 0.1

                                     batch_size: 6

                                     beam_size: 4

                                     clip_grad_norm: 5

                                     command: python model/train.py --model_path experiments --exp_name chart2text --exp_id run1 --train_cs_table_path 'data/train/trainData.txt.pth' --train_sm_table_path 'data/train/trainData.txt.pth' --train_sm_summary_path 'data/train/trainSummary.txt.pth' --valid_table_path 'data/valid/validData.txt.pth' --valid_summary_path 'data/valid/validSummary.txt.pth' --cs_step True --lambda_cs 1 --sm_step True --lambda_sm 1 --label_smoothing '0.05' --sm_step_with_cc_loss False --sm_step_with_cs_proba False --share_inout_emb True --share_srctgt_emb False --emb_dim 512 --enc_n_layers 1 --dec_n_layers 6 --dropout '0.1' --save_periodic 40 --batch_size 6 --beam_size 4 --epoch_size 1000 --max_epoch 81 --eval_bleu True --sinusoidal_embeddings True --encoder_positional_emb True --gelu_activation True --validation_metrics valid_mt_bleu --exp_id "run1"

                                     cs_step: True

                                     cuda: True

                                     dec_n_layers: 6

                                     dropout: 0.1

                                     early_stopping: True

                                     emb_dim: 512

                                     enc_n_layers: 1

                                     encoder_only: False

                                     encoder_positional_emb: True

                                     epoch_size: 1000

                                     eval_bleu: True

                                     eval_cs: False

                                     eval_only: False

                                     exp_id: run1

                                     exp_name: chart2text

                                     gelu_activation: True

                                     group_by_size: True

                                     label_smoothing: 0.05

                                     lambda_cs: 1

                                     lambda_lm: 0

                                     lambda_sm: 1

                                     length_penalty: 1.0

                                     lm_step: False

                                     max_batch_size: 0

                                     max_epoch: 81

                                     max_len: 100

                                     model_path: experiments/chart2text/run1

                                     n_heads: 8

                                     optimizer: adam,lr=0.0001

                                     reload_checkpoint:

                                     reload_emb:

                                     reload_model:

                                     reload_model_strict: False

                                     save_periodic: 40

                                     share_inout_emb: True

                                     share_srctgt_emb: False

                                     sinusoidal_embeddings: True

                                     sm_step: True

                                     sm_step_with_cc_loss: False

                                     sm_step_with_cs_proba: False

                                     split_data: False

                                     stopping_criterion:

                                     tokens_per_batch: -1

                                     train_cs_table_path: data/train/trainData.txt.pth

                                     train_sm_summary_path: data/train/trainSummary.txt.pth

                                     train_sm_table_path: data/train/trainData.txt.pth

                                     valid_summary_path: data/valid/validSummary.txt.pth

                                     valid_table_path: data/valid/validData.txt.pth

                                     validation_metrics: valid_mt_bleu

INFO - 02/11/21 07:40:26 - 0:00:00 - The experiment will be stored in experiments/chart2text/run1

                                    

INFO - 02/11/21 07:40:26 - 0:00:00 - Running command: python model/train.py --model_path experiments --exp_name chart2text --exp_id run1 --train_cs_table_path 'data/train/trainData.txt.pth' --train_sm_table_path 'data/train/trainData.txt.pth' --train_sm_summary_path 'data/train/trainSummary.txt.pth' --valid_table_path 'data/valid/validData.txt.pth' --valid_summary_path 'data/valid/validSummary.txt.pth' --cs_step True --lambda_cs 1 --sm_step True --lambda_sm 1 --label_smoothing '0.05' --sm_step_with_cc_loss False --sm_step_with_cs_proba False --share_inout_emb True --share_srctgt_emb False --emb_dim 512 --enc_n_layers 1 --dec_n_layers 6 --dropout '0.1' --save_periodic 40 --batch_size 6 --beam_size 4 --epoch_size 1000 --max_epoch 81 --eval_bleu True --sinusoidal_embeddings True --encoder_positional_emb True --gelu_activation True --validation_metrics valid_mt_bleu

 

INFO - 02/11/21 07:40:26 - 0:00:00 - ============ Data summary ============

INFO - 02/11/21 07:40:26 - 0:00:00 - Loading dataOld from data/train/trainData.txt.pth ...

INFO - 02/11/21 07:40:26 - 0:00:00 - Removed 0 empty sentences.

 

INFO - 02/11/21 07:40:26 - 0:00:00 - Content-Selection Data -       5703

INFO - 02/11/21 07:40:26 - 0:00:00 - Loading dataOld from data/train/trainData.txt.pth ...

INFO - 02/11/21 07:40:26 - 0:00:00 - Loading dataOld from data/train/trainSummary.txt.pth ...

INFO - 02/11/21 07:40:26 - 0:00:00 - Removed 0 empty sentences.

INFO - 02/11/21 07:40:26 - 0:00:00 - Removed 0 empty sentences.

INFO - 02/11/21 07:40:26 - 0:00:00 - Para Data          -       5703

INFO - 02/11/21 07:40:26 - 0:00:00 - Loading dataOld from data/valid/validData.txt.pth ...

INFO - 02/11/21 07:40:26 - 0:00:00 - Loading dataOld from data/valid/validSummary.txt.pth ...

INFO - 02/11/21 07:40:26 - 0:00:00 - Removed 0 empty sentences.

INFO - 02/11/21 07:40:26 - 0:00:00 - Removed 0 empty sentences.

 

11201

11201

INFO - 02/11/21 07:40:28 - 0:00:03 - Number of parameters (encoder): 10563201

INFO - 02/11/21 07:40:28 - 0:00:03 - Number of parameters (decoder): 30971329

INFO - 02/11/21 07:40:39 - 0:00:13 - ============ Starting epoch 0 ... ============

INFO - 02/11/21 07:40:39 - 0:00:13 - Creating new training dataOld iterator (cs) ...

INFO - 02/11/21 07:40:39 - 0:00:13 - Creating new training dataOld iterator (sm) ...

INFO - 02/11/21 07:40:40 - 0:00:14 -      10 -   68.96 sent/s -  2529.71 words/s - cs:  0.4513 (coef=1.0000) || sm:  7.8071 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:42 - 0:00:16 -      20 -   78.27 sent/s -  3516.20 words/s - cs:  0.3478 (coef=1.0000) || sm:  6.7121 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:43 - 0:00:18 -      30 -   74.59 sent/s -  3292.72 words/s - cs:  0.3351 (coef=1.0000) || sm:  6.6170 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:45 - 0:00:19 -      40 -   77.04 sent/s -  4008.87 words/s - cs:  0.3170 (coef=1.0000) || sm:  6.3595 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:47 - 0:00:21 -      50 -   66.91 sent/s -  2994.82 words/s - cs:  0.3230 (coef=1.0000) || sm:  6.1247 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:49 - 0:00:23 -      60 -   65.51 sent/s -  3321.71 words/s - cs:  0.3013 (coef=1.0000) || sm:  5.8914 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:50 - 0:00:25 -      70 -   66.09 sent/s -  3379.25 words/s - cs:  0.2899 (coef=1.0000) || sm:  6.2185 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:52 - 0:00:26 -      80 -   73.47 sent/s -  3375.93 words/s - cs:  0.3022 (coef=1.0000) || sm:  5.9257 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:54 - 0:00:28 -      90 -   72.98 sent/s -  3185.13 words/s - cs:  0.3270 (coef=1.0000) || sm:  5.4492 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:55 - 0:00:30 -     100 -   69.30 sent/s -  3262.27 words/s - cs:  0.3137 (coef=1.0000) || sm:  5.7490 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:57 - 0:00:31 -     110 -   72.89 sent/s -  2969.77 words/s - cs:  0.3711 (coef=1.0000) || sm:  5.6494 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:40:59 - 0:00:33 -     120 -   71.88 sent/s -  3695.00 words/s - cs:  0.2364 (coef=1.0000) || sm:  6.0095 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:00 - 0:00:34 -     130 -   75.35 sent/s -  3186.87 words/s - cs:  0.4176 (coef=1.0000) || sm:  5.6705 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:02 - 0:00:36 -     140 -   73.13 sent/s -  3527.84 words/s - cs:  0.2764 (coef=1.0000) || sm:  5.5755 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:04 - 0:00:38 -     150 -   71.10 sent/s -  3281.80 words/s - cs:  0.2828 (coef=1.0000) || sm:  5.5979 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:05 - 0:00:39 -     160 -   70.62 sent/s -  3229.74 words/s - cs:  0.4042 (coef=1.0000) || sm:  5.8364 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:07 - 0:00:41 -     170 -   69.03 sent/s -  3388.08 words/s - cs:  0.2873 (coef=1.0000) || sm:  6.0097 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:09 - 0:00:43 -     180 -   71.19 sent/s -  3323.44 words/s - cs:  0.2447 (coef=1.0000) || sm:  5.3536 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:10 - 0:00:45 -     190 -   69.75 sent/s -  2922.97 words/s - cs:  0.3147 (coef=1.0000) || sm:  5.3522 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:12 - 0:00:46 -     200 -   69.12 sent/s -  2966.24 words/s - cs:  0.4073 (coef=1.0000) || sm:  5.5942 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:14 - 0:00:48 -     210 -   68.57 sent/s -  3138.58 words/s - cs:  0.3412 (coef=1.0000) || sm:  5.7256 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:16 - 0:00:50 -     220 -   70.71 sent/s -  3421.93 words/s - cs:  0.2274 (coef=1.0000) || sm:  5.7425 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:17 - 0:00:51 -     230 -   76.90 sent/s -  3552.27 words/s - cs:  0.2384 (coef=1.0000) || sm:  5.7137 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:19 - 0:00:53 -     240 -   74.87 sent/s -  3034.86 words/s - cs:  0.3194 (coef=1.0000) || sm:  5.3719 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:20 - 0:00:55 -     250 -   72.67 sent/s -  3240.91 words/s - cs:  0.3054 (coef=1.0000) || sm:  5.3976 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:22 - 0:00:56 -     260 -   73.87 sent/s -  3425.23 words/s - cs:  0.2505 (coef=1.0000) || sm:  5.9005 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:24 - 0:00:58 -     270 -   73.14 sent/s -  4033.18 words/s - cs:  0.2593 (coef=1.0000) || sm:  5.4089 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:25 - 0:00:59 -     280 -   73.57 sent/s -  2904.76 words/s - cs:  0.3463 (coef=1.0000) || sm:  5.4932 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:27 - 0:01:01 -     290 -   73.55 sent/s -  3080.31 words/s - cs:  0.3115 (coef=1.0000) || sm:  5.4806 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:28 - 0:01:03 -     300 -   79.06 sent/s -  3489.20 words/s - cs:  0.2681 (coef=1.0000) || sm:  5.4723 (coef=1.0000) - Transformer LR = 1.0000e-04             

INFO - 02/11/21 07:41:30 - 0:01:04 -     310 -   80.42 sent/s -  3794.40 words/s - cs:  0.2895 (coef=1.0000) || sm:  5.5419 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:32 - 0:01:06 -     320 -   78.95 sent/s -  3690.99 words/s - cs:  0.3184 (coef=1.0000) || sm:  5.7453 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:33 - 0:01:07 -     330 -   74.40 sent/s -  3328.03 words/s - cs:  0.3050 (coef=1.0000) || sm:  5.6414 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:35 - 0:01:09 -     340 -   76.31 sent/s -  3346.92 words/s - cs:  0.3396 (coef=1.0000) || sm:  5.7215 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:36 - 0:01:10 -     350 -   74.00 sent/s -  3401.63 words/s - cs:  0.2706 (coef=1.0000) || sm:  5.5729 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:38 - 0:01:12 -     360 -   73.18 sent/s -  3127.16 words/s - cs:  0.2803 (coef=1.0000) || sm:  5.4317 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:40 - 0:01:14 -     370 -   76.01 sent/s -  3143.13 words/s - cs:  0.3841 (coef=1.0000) || sm:  5.1901 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:41 - 0:01:15 -     380 -   80.86 sent/s -  3957.96 words/s - cs:  0.3317 (coef=1.0000) || sm:  5.7270 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:43 - 0:01:17 -     390 -   75.83 sent/s -  3360.98 words/s - cs:  0.2898 (coef=1.0000) || sm:  5.1303 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:44 - 0:01:18 -     400 -   77.50 sent/s -  3300.93 words/s - cs:  0.2528 (coef=1.0000) || sm:  5.1625 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:46 - 0:01:20 -     410 -   81.46 sent/s -  3742.48 words/s - cs:  0.2846 (coef=1.0000) || sm:  5.3981 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:47 - 0:01:21 -     420 -   77.86 sent/s -  2821.27 words/s - cs:  0.4389 (coef=1.0000) || sm:  4.9903 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:49 - 0:01:23 -     430 -   70.96 sent/s -  3826.58 words/s - cs:  0.2616 (coef=1.0000) || sm:  5.5440 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:51 - 0:01:25 -     440 -   70.34 sent/s -  3070.82 words/s - cs:  0.3127 (coef=1.0000) || sm:  5.3859 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:52 - 0:01:26 -     450 -   71.94 sent/s -  3496.44 words/s - cs:  0.3243 (coef=1.0000) || sm:  5.5641 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:54 - 0:01:28 -     460 -   70.68 sent/s -  3442.76 words/s - cs:  0.2823 (coef=1.0000) || sm:  5.6922 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:56 - 0:01:30 -     470 -   70.73 sent/s -  3271.72 words/s - cs:  0.3634 (coef=1.0000) || sm:  5.2747 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:57 - 0:01:31 -     480 -   75.83 sent/s -  3427.12 words/s - cs:  0.3127 (coef=1.0000) || sm:  5.6401 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:41:59 - 0:01:33 -     490 -   74.71 sent/s -  3562.86 words/s - cs:  0.2697 (coef=1.0000) || sm:  5.5677 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:00 - 0:01:34 -     500 -   78.54 sent/s -  3595.84 words/s - cs:  0.2857 (coef=1.0000) || sm:  5.0777 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:02 - 0:01:36 -     510 -   77.29 sent/s -  3562.29 words/s - cs:  0.2981 (coef=1.0000) || sm:  5.6249 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:03 - 0:01:38 -     520 -   80.52 sent/s -  3961.42 words/s - cs:  0.2707 (coef=1.0000) || sm:  5.3959 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:05 - 0:01:39 -     530 -   74.81 sent/s -  2949.84 words/s - cs:  0.2745 (coef=1.0000) || sm:  4.9403 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:07 - 0:01:41 -     540 -   76.11 sent/s -  3598.08 words/s - cs:  0.2301 (coef=1.0000) || sm:  5.3436 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:08 - 0:01:42 -     550 -   71.80 sent/s -  3284.73 words/s - cs:  0.3230 (coef=1.0000) || sm:  5.2335 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:10 - 0:01:44 -     560 -   72.86 sent/s -  3159.57 words/s - cs:  0.3212 (coef=1.0000) || sm:  4.9024 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:12 - 0:01:46 -     570 -   71.12 sent/s -  3145.22 words/s - cs:  0.3385 (coef=1.0000) || sm:  5.4852 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:13 - 0:01:47 -     580 -   74.55 sent/s -  3670.83 words/s - cs:  0.2041 (coef=1.0000) || sm:  5.1635 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:15 - 0:01:49 -     590 -   76.28 sent/s -  3253.96 words/s - cs:  0.3591 (coef=1.0000) || sm:  5.6365 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:16 - 0:01:50 -     600 -   75.96 sent/s -  3794.87 words/s - cs:  0.2789 (coef=1.0000) || sm:  5.3166 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:18 - 0:01:52 -     610 -   76.07 sent/s -  3359.69 words/s - cs:  0.2447 (coef=1.0000) || sm:  5.2666 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:19 - 0:01:54 -     620 -   76.89 sent/s -  3165.51 words/s - cs:  0.2570 (coef=1.0000) || sm:  4.9742 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:21 - 0:01:55 -     630 -   75.70 sent/s -  3568.67 words/s - cs:  0.3021 (coef=1.0000) || sm:  5.1113 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:23 - 0:01:57 -     640 -   73.30 sent/s -  3422.69 words/s - cs:  0.2535 (coef=1.0000) || sm:  4.9967 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:24 - 0:01:59 -     650 -   70.91 sent/s -  2821.49 words/s - cs:  0.3569 (coef=1.0000) || sm:  5.1334 (coef=1.0000) - Transformer LR = 1.0000e-04

INFO - 02/11/21 07:42:26 - 0:02:00 -     660 -   69.23 sent/s -  3299.94 words/s - cs:  0.2695 (coef=1.0000) || sm:  4.9700 (coef=1.0000) - Transformer LR = 1.0000e-04

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [43,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [46,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [47,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [48,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [63,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [43,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [46,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [47,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [48,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

/pytorch/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [463,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

Traceback (most recent call last):

  File "model/train.py", line 229, in <module>

    main(params)

  File "model/train.py", line 197, in main

    trainer.content_selection_step(params.lambda_cs)

  File "/red/ssd/appl/ai_hub/model_zoo/Chart2Text/Chart2Text/model/src/trainer.py", line 316, in content_selection_step

    alen = torch.arange(lengths.max(), dtype=torch.long, device=lengths.device)

RuntimeError: CUDA error: device-side assert triggered

**Comment by jalalirs** [comment]
I solved this by increasing the hard coded position_embedding size from 800 to 1200 since apparently there are some sentences with maximum position >= 1180
